name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face Space
        run: git push https://${{ vars.shihir7744 }}:${{ secrets.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 }}@huggingface.co/spaces/${{ vars.shihir7744 }}/${{ vars.n8n }} main


