name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to Hugging Face Space (Force)
        env:
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          HF_SPACE_NAME: ${{ vars.HF_SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME}
          git push hf main --force
